### ISSUE TITLE
FYI: Another related library

### ISSUE THREAD

**Issue by megamattron** [tslamic/AndroidDeviceNames#3]
Hi! I saw your project on the github email list and just thought you might want to know about another approach to the same problem over here: https://gist.github.com/jaredrummler/16ed4f1c14189375131d

We've been using that for a few months and it seems to cover a good number of the devices.

Just thought you might be interested.

**Comment by tslamic** [comment]
Hi Matt,

many thanks for taking the time to comment. I’ve seen the snippet, and it does seem to cover all devices supported by Google Play, which is cool.

I’ve taken a slightly different approach with this lib, taking memory into account. It does support less devices, but having a [Python generator](https://github.com/tslamic/AndroidDeviceNames/blob/master/generator/adn.py), they can easily be added. I thought it might be a good alternative.

Always good to have options though, so thanks again for bringing this up. :+1:

**Comment by bzkdjc** [comment]
At least, we can use both, thanks to the failback supplied only by yours': 

``` java
DeviceNames.getCurrentDeviceName(Devices.getDeviceName())
```

**Comment by AngusMorton** [comment]
@bzkdjc

By calling `DeviceNames.getCurrentDeviceName(Devices.getDeviceName())`, `Devices.getDeviceName()`has already been executed by the time you enter `getCurrentDeviceName`. Which means you end up doing the work twice. 

So there isn't any point in doing the `DeviceNames.getCurrentDeviceName()` call at that point.

**Comment by bzkdjc** [comment]
@beamishjabberwock 
Thank you! :) 
You're right. I didn't pay attention to that.

_But, at least that means that I only rely on `DeviceNames` result at first, because even if `Devices` is called first, the result of `DeviceNames.getCurrentDeviceName(Devices.getDeviceName())` is to only give back `Devices` answer only if `DeviceNames` call (called at 2nd position) were unsuccessful._

**Comment by AngusMorton** [comment]
As a 'work-around':

``` java
  String name = DeviceNames.getCurrentDeviceName(null);
  if (name == null) {
    name = Devices.getDeviceName();
  }
```

**Comment by jaredrummler** [comment]
Just wanted to comment that the gist in the OP is outdated. I created a library project here: https://github.com/jaredrummler/AndroidDeviceNames

It is a little larger than this library but it covers 10,000+ devices.
