### ISSUE TITLE
Manifest merge conflict

### ISSUE THREAD

**Issue by zsoltk** [tslamic/AndroidDeviceNames#4]
Hello,

Including the lib generates this error:

```
Error:(10, 9) Attribute application@label value=(My Example App) from AndroidManifest.xml:10:9
    is also present at com.github.tslamic.adn:library:1.0:13:9 value=(@string/app_name)
    Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:8:5 to override
```

Surely, the tools:replace solution works, but it would be so nice not to have to do this :)

**Comment by tslamic** [comment]
Hi Zsolt,

thanks for reporting this. Unfortunately, I’m unable to reproduce it. Could you please tell me the steps you took? I’ve imported the lib as a module, .aar and a maven artifact without any problems.

**Comment by zsoltk** [comment]
I used the Gradle dependency:

`compile 'com.github.tslamic.adn:library:1.0'`

Have a `@string/app_name` resource just as the lib does, and they will collide.

Since this is a library, is there any need for the application tag in your manifest file?

**Comment by tslamic** [comment]
Hi Zsolt,

funny, I specifically tried it with a `@string/app_name` in my sample app too, to see if this really was the problem, but it compiled without complaining. Which version of Android Studio do you use?

Anyhow, I’ll consider removing the `application:label` tag, it does seem it’s redundant. Thanks again for reporting this.

**Comment by zsoltk** [comment]
Unfortunately this does not depend on Android Studio, but rather the gradle build tools version. Problem is, I'm pretty much stuck with an older version of it on this particular project for now, which cannot be updated easily. So this is rather a compatibility problem :)

Searching for the error message I found some issues posted on other github projects with this same exact problem. The project owners solved it there by removing the tag, too.

Thanks in advance!
Cheers
