### ISSUE TITLE
Script to update SQLite db

### ISSUE THREAD

**Issue by corcoran** [tslamic/AndroidDeviceNames#8]
Do you have a script that you're using to update the sqlite db?  The official Android list of supported devices that populates the DB unfortunately isn't an accurate reflection of the actual model a lot of vendors use in their builds and it might make sense to have a separate JSON file with a script that anyone can use to create their own db file from.

**Comment by tslamic** [comment]
Hi Jeff,

you can find the script in the `generator` folder. For some reason - which I cannot recall - I only generated the database using Google Play CSV. Running the script now results in about ~25k devices, but will wait for a day or so (in case you come up with any updates), before updating the lib.

Thanks,
Tadej
